spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LearningHub
    username: postgres
    password: password

  jpa:
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    #properties:
    #hibernate:
    #dialect:org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  # App Properties
intuit:
  app:
    jwtSecret: intuitSecretKey
    jwtExpirationMs: 86400000

server:
  port: 8083
